default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ror
  password: myRoR
  host: localhost

development:
  <<: *default
  database: zt_api_server_development

test:
  <<: *default
  database: zt_api_server_test

production:
  <<: *default
  database: zt_api_server_production
  username: mysql
  password: <%= ENV['MYSQL_DATABASE_PASSWORD'] %>
